# Generated by Django 5.2.5 on 2025-09-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150, verbose_name='Nombre del Solicitante')),
                ('documento_de_identidad', models.CharField(max_length=50, verbose_name='Documento de Identidad')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono_de_contacto', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('tipo_de_solicitud', models.CharField(choices=[('ACADEMICA', 'Académica'), ('ADMINISTRATIVA', 'Administrativa'), ('TECNICA', 'Técnica'), ('OTRA', 'Otra')], max_length=20, verbose_name='Tipo de Solicitud')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción Detallada')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
